config/routes.rb
Rails.application.routes.draw do
  get 'tests/index'
  root 'tests#start'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :users, only: %i[index show]
  resources :questions do
    resources :answers
    post :right
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  attr_accessor :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable


           def self.find_for_database_authentication(warden_conditions)
             conditions = warden_conditions.dup
             login = conditions.delete(:login)
             where(conditions).where(['lower(email) = :value OR lower(email) = :value', { value: login.strip.downcase }]).first
           end


end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login
  #scope :featured, order('rating DESC')
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         has_attached_file :avatar, default_url: '/assets/missing.png'
         validates_attachment_content_type :avatar, content_type: ['image/jpeg', 'image/gif', 'image/png']

         def self.find_for_database_authentication(warden_conditions)
           conditions = warden_conditions.dup
           login = conditions.delete(:login)
           where(conditions).where(['lower(username) = :value OR lower(email) = :value', { value: login.strip.downcase }]).first
         end

         def self.find_recoverable_or_initialize_with_errors(required_attributes, attributes, error = :invalid)
           (case_insensitive_keys || []).each { |k| attributes[k].try(:downcase!) }

           attributes = attributes.slice(*required_attributes)
           attributes.delete_if { |_key, value| value.blank? }

           if attributes.keys.size == required_attributes.size
             if attributes.key?(:login)
               login = attributes.delete(:login)
               record = find_record(login)
             else
               recusernameord = where(attributes).first
             end
           end
         end

         def self.find_record(login)
           where(['username = :value OR email = :value', { value: login }]).first
         end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!

  def create
  	params[:answer][:question_id] = params[:question_id]
  	@answer = Answer.create(answer_params)
    if @answer.save
    else
      @answer.errors.full_messages.each do |msg|
       @msg = msg
      end
      flash[:notice] = "#{@msg}"
    end
    redirect_to tests_index_path
  end

  def destroy
      @question = Question.find(params[:question_id])
      @answer = @question.answer.find(params[:id])
      @answer.destroy
      redirect_to tests_index_path
    end
  private

  	def answer_params
  		params.require(:answer).permit(:text, :question_id, :right)
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username email password password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[login password password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[avatar username email password password_confirmation current_password])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_question, only: [:show,:edit,:update,:destroy]

  def new
   @question = Question.new
  end

  def show
      @answers = Answer.where(question_id: @question.id)
      @answer = Answer.new
      respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    if current_user.admin
    @question = Question.new(questions_params)
      if @question.save
        redirect_to root_path
      else
        render 'new'
      end
    end
  end

  def destroy
    if @question.nil?
      redirect_to root_path
    else
    @question.destroy
    redirect_to root_path
  end
  end

  def edit
  end

  def update
    @question.update(questions_params)
    redirect_to root_path
  end


  def right
    @flag = false
    @question = Question.find(params[:question_id])
    @user_answer = params[:user_answer]
    Answer.where(id: @user_answer).each do |x|
      if x.right
        @flag=true
    current_user.rating += 1
    current_user.save
        break
      end
    end
    respond_to do |format|
      format.js
    end

  end

  private

    def questions_params
      params.require(:question).permit(:text)
    end

    def find_question
      @question = Question.find(params[:id])
    end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!
  def index
    @questions = Question.all
    @x=1
    @result=0
  end

  def start

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: %i[show]
  def index
    @users = User.all.order('rating DESC')
  end

  def show
  end


  private

   def find_user
   @user = User.find(params[:id])
   end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<div class="nav">
  <%= link_to 'UzNU Tests', root_path, :class => 'nav-item' %>
  <div class="nav-right">
    <div class="grid">
      <% if user_signed_in? %>
        <li>
          <%= link_to "Rating" , users_path , :class => 'nav-item'%>
        </li>
        <li class="nav-item">Logged in as
          <strong>
            <%= link_to current_user.username , user_path(current_user) , :class => 'nav-item'%></strong>
        </li>
        <%= link_to destroy_user_session_path, method: :delete, :class => 'nav-item' do %>
        Logout
        <i class="fas fa-sign-out-alt"></i>
      <% end %>
    <% else %>
      <li>
        <%= link_to "Rating" , users_path , :class => 'nav-item'%>
      </li>
      <li><%= link_to new_user_registration_path, :class => 'nav-item' do %>
        Sign up
        <i class="fas fa-user-plus"></i>
      <% end %>
    </li>
    <li><%= link_to new_user_session_path, :class => 'nav-item' do %>Login
      <i class="fas fa-sign-in-alt"></i>
    <% end %>
  </li>
<% end %>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KursovaVar1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<div class="form-group">
  <label for="question" class="cols-sm-2 control-label">
    <p><%= f.label "Question" %></p>
  </label>
  <div class="cols-sm-10">
    <div class="input-group">
      <%= f.text_field :text, placeholder: "Enter your Question", type: "text", class: "form-control"%>
    </div>
  </div>
</div>
<div class="form-group">
  <p><%= f.submit "Save", class: "btn btn-primary btn-lg btn-block login-button", id: "button" %></p>
</div>

app/views/questions/_showmodal.html.erb
<div class="modal" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title"><%= @question.text %></h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <!-- Modal body -->
      <div class="modal-body">
        <%=form_for :right, url: question_right_path(@question.id), method: :post, html: {class: 'form-signin'}, remote: true do |f|%>
          <div class="container">
            <% @answers.each do |answer|%>
              <div class="row">
                <div class="col-md-9 col-xs-12 col-sm-9  col-lg-6">
                    <label>
                      <h5><%= radio_button_tag 'user_answer', answer.id %>
                      <%= answer.text%></h5>
                    </label>
                </div>
              </div>
            <% end %>
            <p> <%= f.submit "Confirm", :class => 'subm'%></p>
          </div>
        <% end %>
      </div>
      <!-- Modal body if user admin -->
      <div class="modal-body">
        <% if current_user and current_user.admin %>
          <hr>
          <%= form_for @answer, url:question_answers_path(@question.id) do |f| %>
            <%= f.label "Add Answer"%>
            <p><%= f.text_field :text, placeholder: "Enter your Answer"%> <%= f.submit "Add" , :class => 'subm'%></p> <br>
            <p><%= f.check_box(:right)%> Correct?</p>
          <%end%>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="container">
  <div class="row main">
    <div class="main-login main-center">
      <center><%= form_for @question, url: questions_path do |f| %>
        <% if @question.errors.any? %>
          <% @question.errors.full_messages.each do |msg| %>
            <li><%=msg%></li>
          <%end%>
        <%end%>
        <%= render 'questions/form', f:f%>
      <%end%>
    </center>
</div>
</div>
</div>

app/views/questions/right.js.erb
<% if @flag == true %>
	$("#myModal").hide();
	$(".modal-backdrop").hide();
	$("#question_<%= @question.id %> a button").addClass('green').attr("disabled", true).text('Correct');
<% else %>
	$("#myModal").hide();
	$(".modal-backdrop").hide();
	$("#question_<%= @question.id %> a button").addClass('red').attr("disabled", true).text('Wrong');
<% end %>

app/views/questions/show.js.erb
$('#question').html("<%= j render 'questions/showmodal' %>");
$('#myModal').modal('show');

app/views/users/_user.html.erb
<%= user.username%>
<%= image_tag user.avatar.url,style:"width:100px;"%>
<% user.rating%>
<%= link_to "Profile", user_path(user.id)%>
<hr>

app/views/users/index.html.erb
<%= render @users%>

app/views/users/show.html.erb
<div class="profile">
  <div class="row">
    <%= image_tag @user.avatar.url, :class => 'img'%>
    <div class="info">
      <strong>User name: </strong> <%= @user.username%> <br>
      <strong>Email: </strong><%= @user.email%> <br>
      <strong>Rating: </strong><%= @user.rating%> <br>
      <% if @user.id == current_user.id  && user_signed_in? %>
      <%= link_to "Setting",edit_user_registration_path%>
      <% end %>
    </div>
  </div>
</div>